import './globals.scss';
import type { Metadata } from 'next';
import {} from 'next/font/google';
import { Session } from 'next-auth';
import NextAuthProvider from './components/providers/NextAuthProvider';
import ReactQueryClientProvider from './components/providers/ReactQueryClientProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	session,
}: Readonly<{
	children: React.ReactNode;
	session: Session;
}>) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvider session={session}>
					<ReactQueryClientProvider>{children}</ReactQueryClientProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
