import './globals.scss';
import NextAuthProvider from './components/providers/NextAuthProvider';
import ReactQueryClientProvider from './components/providers/ReactQueryClientProvider';
import Header from './components/layout/Header';
import Main from './components/layout/Main';
import type { Metadata } from 'next';
import { Session } from 'next-auth';

export const metadata: Metadata = {
	title: 'Todo App',
	description: 'Generated by create next app',
	icons: 'icon.svg',
};

export default function RootLayout({
	children,
	session,
}: Readonly<{
	children: React.ReactNode;
	session: Session;
}>) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvider session={session}>
					<ReactQueryClientProvider>
						<Header />
						<Main>{children}</Main>
					</ReactQueryClientProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
